# Generated by Django 3.2.2 on 2022-07-25 17:40

from django.db import migrations, models

from .constants import DEFAULT_QUOTES


def create_default_quotes(apps, schema_editor):
    """Function for create initial data."""
    Quote = apps.get_model('quotes', 'Quote')
    if not Quote.objects.exists():
        Quote.objects.bulk_create(
            [
                Quote(**quote_data)
                for quote_data in DEFAULT_QUOTES
            ]
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('author', models.CharField(max_length=128, verbose_name='Автор цитаты')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'unique_together': {('text', 'author')},
            },
        ),
        migrations.RunPython(create_default_quotes),
    ]
