# Generated by Django 3.2.2 on 2022-07-30 08:37

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pockets', '0005_alter_transactioncategory_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя цели')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма цели')),
                ('initial_deposit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Начальный вклад')),
                ('deposit_term', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок(месяцы)')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Процент')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата создания цели')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершена ли цель')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='pockets.transactioncategory', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TargetTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Изменение баланса')),
                ('from_percent', models.BooleanField(default=False, verbose_name='Пришли ли деньги с процентов')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='targets.target', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Операция цели',
                'verbose_name_plural': 'Операции целей',
            },
        ),
    ]
