# Generated by Django 3.2.2 on 2022-07-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategory',
            name='category_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default=0, max_length=7, verbose_name='Тип операции'),
            preserve_default=False,
        ),
    ]
