# Generated by Django 3.2.2 on 2022-07-11 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0003_auto_20220712_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pockets.transactioncategory', verbose_name='Категория'),
        ),
    ]
